configName: same54_lan9252_click
folderName: same54_lan9252_click
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAME54P20A
projectName: ethercat_counter_foe_app
settings:
  PackageFilter: csp;ethercat;quick_docs;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.4.70\atdf\ATSAME54P20A.atdf
