format_version: v1.0
type: UniqueComponent
attributes: {id: tc0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_TIME_COMPONENT_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: sys_time}
  - type: Boolean
    attributes: {id: TC_SYS_TIME_CONNECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'true'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TC0_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: ethercat_lan9252}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: LAN9252_TMR_Dependency}
- type: ElementPosition
  attributes: {x: '18', y: '233', id: tc0}
